
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.shrinkpath]
audit-as-crates-io = true

[[exemptions.anstream]]
version = "0.6.21"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.13"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.1.5"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.11"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.60"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.5.60"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.55"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.is_terminal_polyfill]]
version = "1.70.2"
criteria = "safe-to-deploy"

[[exemptions.once_cell_polyfill]]
version = "1.70.2"
criteria = "safe-to-deploy"

[[exemptions.shrinkpath]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.117"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"
